Feature/add coverage python
martis42/depend_on_what_you_use pull request #25
Opened 2022-03-29 17:18 UTC by BayerC

in progress

2022-03-31 17:00 UTC, martis42 requested changes

2022-04-05 18:08 UTC, BayerC commented on .github/workflows/ci.yml
> +name: CI
done

2022-04-05 18:08 UTC, BayerC commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
done

2022-04-05 18:12 UTC, martis42 approved these changes

2022-04-05 18:12 UTC, merged